version: "3"

services:
  postgres-db:
    image: postgres:latest
    restart: always

    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker

    ports:
      - 5432:5432

    volumes: 
      - ./database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
